name: Build App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-stable:
    name: Build the Glider in stable Xcode
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['12.5.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select  ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app
          xcode-select -p
        env:
          XCODE_VERSION: ${{ matrix.xcode }}
      - name: Build
        run: xcodebuild -scheme Glider -project Glider.xcodeproj -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
  build-beta:
    name: Build the Glider in beta Xcode
    runs-on: macos-11
    needs: build-stable
    strategy:
      matrix:
        xcode: ['13.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select  ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app
          xcode-select -p
        env:
          XCODE_VERSION: ${{ matrix.xcode }}
      - name: Build
        run: xcodebuild -scheme Glider -project Glider.xcodeproj -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
