name: Build App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Glider scheme
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['12.5.1', '13.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select  ${{ matrix.xcode }}
        run: |
          xcode-select -s /Applications/Xcode_$XCODE_VERSION.app
          xcode-select -p
        env:
          XCODE_VERSION: ${{ matrix.xcode }}
      - name: Build
        run: xcodebuild
